/**
 * Seed script: Inserts classified Reddit threads from social listening analysis.
 * Run with: npx tsx src/db/seed-reddit.ts
 */

import { db } from "./index.js";
import { redditThreads } from "./schema.js";
import { sql } from "drizzle-orm";

const threads = [
  // ─── r/FemaleHairLoss ───────────────────────────────────
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sf8wk7",
    title: "Experiencing the worst case of PP hair loss",
    body: "This is currently the top view of my head, second pic is every three days worth of hair lost. I have always had thin fine hair but this is nothing like I have ever seen. At around 12 weeks postpartum the shedding started, and currently at 5 months postpartum it's getting worse. I've been taking the postpartum Nutrafol for about 8 weeks now. Using satin pillowcases, cut it short into a bob, changed shower head to filter out hard water.",
    author: "Fit-Office-8716",
    score: 69,
    commentCount: 14,
    sentiment: "negative",
    relevantBrands: ["Nutrafol"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sesusr",
    title: "crashed out on my dermatologist because i'm losing everything",
    body: "I'm 19 and I've been losing hair like crazy. Testing vegamour shampoo, nutrafol every night, 5% kirkland minoxidil dropper 2x a day, olaplex leave in treatment, dermarolling with vegamour 0.25mm needles. It's really getting to me mentally. I've always had crazy thick unruly hair as an asian female and it just feels like I'm losing so much of myself now.",
    author: "DiverVirtual7928",
    score: 25,
    commentCount: 14,
    sentiment: "negative",
    relevantBrands: ["Vegamour", "Nutrafol", "Olaplex"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1seg2bm",
    title: "A year and some change on triple therapy (min, spi, and fin)!",
    body: "Just wanted to share some progress. Previously tried topical minox, microneedling with minox, DHT blocker pills from Amazon, and Nutrafol to incredibly lukewarm results. Now on oral minoxidil 2.5mg, spironolactone 100mg, finasteride 2.5mg. With hair fibers and hairline powders, I finally feel like a normal girl.",
    author: "Studi0Jiggly",
    score: 16,
    commentCount: 4,
    sentiment: "positive",
    relevantBrands: ["Nutrafol"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sbd59e",
    title: "Stressed about extreme hair loss",
    body: "23F here, my hair has been falling in this pattern. I do use rosemary oil sometimes and L'Oreal Elvive Growth Booster Scalp Serum, however, not being consistent with them.",
    author: "Peanutbutter_2003",
    score: 60,
    commentCount: 10,
    sentiment: "negative",
    relevantBrands: ["L'Oreal Elvive"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sftggq",
    title: "Hair growth (non alopecia) - iron and vitamin D supplementing works",
    body: "For the past few years I've had thinning hair from medication, underactive thyroid, and low iron/vit D levels. Over the past 3 months supplementing with 105mg daily iron and 3000iu vit D3. I've gone from loads of hair falling out to only 25 or so hairs. Started using a hair serum in my middle part. MooGoo brand.",
    author: "One_Waxed_Wookiee",
    score: 2,
    commentCount: 1,
    sentiment: "positive",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sbvuy8",
    title: "Hair Serums and Minoxidil - Kerastase Genesis vs The Ordinary",
    body: "I'm a 21yr old Female and the past few years I've started shedding a lot of hair and my hairline is receding. I've heard great things about the Kerastase Genesis serum and the Ordinary Multi peptide serum for hair density. But I cannot decide which one is better. Also many people said that Minoxidil only works for as long as you keep using it. Is that true?",
    author: "Own_Task_4665",
    score: 2,
    commentCount: 5,
    sentiment: "neutral",
    relevantBrands: ["The Ordinary", "Kerastase"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sdgds7",
    title: "PCOS hair loss - The Ordinary and elvive serums",
    body: "I'm 17 and recently diagnosed with PCOS, androgenic alopecia for the last 6 months. Started spironolactone 3 weeks ago. Is taking pumpkin seed capsules or saw palmetto actually worth it? Do the ordinary hair density or elvive growth booster serums actually work, and is the aminexil dangerous for pets?",
    author: "420blazinittt",
    score: 2,
    commentCount: 2,
    sentiment: "neutral",
    relevantBrands: ["The Ordinary", "L'Oreal Elvive"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1scrm2t",
    title: "Am I a good candidate for minoxidil? (18F accutane damage)",
    body: "I went on accutane at 15, during and after I started experiencing hair shedding. It's been two years and it has not stopped. I'm starting on 50mg of spironolactone. I want to start topical minoxidil but I'm nervous about the shedding phase. Will it lose potency? Can I use it on my eyebrows? I purchased the Kerastase Genesis Scalp Serum and the Ordinary Hair Peptide Serum.",
    author: "agskxgskshsk",
    score: 3,
    commentCount: 4,
    sentiment: "neutral",
    relevantBrands: ["The Ordinary", "Kerastase"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sf7kdf",
    title: "Can you have telogen effluvium for years or do I need to accept I have AGA",
    body: "My hair loss started in 2024 during a very stressful time and has never stopped. My dermatologist keeps suggesting it could be stress-related, but since March 2024 I have lost about half of my hair due to increased hair shedding. I don't know why my derm keeps suggesting it is stress.",
    author: "coopcong",
    score: 2,
    commentCount: 5,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sgf2q2",
    title: "Losing 500 hairs daily all of a sudden. Product recommendations?",
    body: "25F noticing a lot of hair shedding recently. Hair gets very oily. Using nizoral. Had extreme stress December to January. Got tested - no deficiencies. Can you please suggest a daily serum that can help strengthen my roots?",
    author: "Other_Direction2301",
    score: 2,
    commentCount: 3,
    sentiment: "neutral",
    relevantBrands: ["Nizoral"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1safr15",
    title: "Spironolactone hair shedding, need help",
    body: "I've been taking 25 mg daily for acne for 6 weeks, it's already helping. But about 3 weeks after starting spiro, my hair began shedding like crazy. I've never had any issues with hair loss before spironolactone.",
    author: "Acceptable-City-161",
    score: 2,
    commentCount: 7,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sayv6j",
    title: "Advice on starting/stopping treatment - Nutrafol vs minoxidil before wedding",
    body: "Experiencing hair loss possibly from ozempic. Started nutrafol last month, then got oral minoxidil. My wedding is 6 months away and I'd really like to look and feel my best! Wondering about dread shed experiences.",
    author: "nicolehey",
    score: 1,
    commentCount: 0,
    sentiment: "neutral",
    relevantBrands: ["Nutrafol"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sevzy5",
    title: "Ferritin levels and hair shedding",
    body: "Noticed hair shedding beginning of September. Ferritin was 101 but higher due to being sick. Rechecked yesterday and it's 67.6. Could this still be a cause for hair loss even though it's on the higher end?",
    author: "Consistent_Bat_9552",
    score: 1,
    commentCount: 3,
    sentiment: "neutral",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sesjn0",
    title: "Need advice - considering Nutrafol then Hers minoxidil after graduation",
    body: "More hair shedding lately, thinning around temples, hairline, and back of head. Thinking about Minoxidil but nervous about initial shedding phase since I'm graduating in May. Was considering trying Nutrafol for now then starting Minoxidil from Hers after graduation.",
    author: "UnitedSecret3889",
    score: 1,
    commentCount: 2,
    sentiment: "neutral",
    relevantBrands: ["Nutrafol", "Hers"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1se3bgt",
    title: "Topical minoxidil and sleep issues",
    body: "Had massive hair shedding starting in October. Hairdresser noticed alopecia areata at crown. Using clobetasol, pumpkin seed oil with saw palmetto, iron supplement, biotin. Used topical minoxidil for two weeks but had such vivid dreams I stopped. Don't like the idea of using it forever.",
    author: "Cuddlecat2611",
    score: 1,
    commentCount: 7,
    sentiment: "mixed",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sfd7ym",
    title: "TE recovery 4 months of progress - The Ordinary + Nutrafol",
    body: "Lost 30% of hair from extreme stress. Using cheapest iRestore helmet every other day, 2% ketoconazole shampoo, scalp massage, dermastamping. Added The Ordinary hair density serum in late January. Just started vegan Nutrafol. Ferritin went from 9 to 24. I never had thick hair, very fine and straight.",
    author: "Prudent_Specific_500",
    score: 14,
    commentCount: 0,
    sentiment: "positive",
    relevantBrands: ["The Ordinary", "Nutrafol"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sgoc2s",
    title: "Pregnancy hormones are wild - dreading postpartum hair loss",
    body: "Was having substantial hair loss behind both ears, possibly tied to autoimmune disease. Currently pregnant and my hair is back to its old self. Not looking forward to postpartum hair loss. Any and all advice to prep for that is welcome!",
    author: "happy_go_luck_e",
    score: 3,
    commentCount: 2,
    sentiment: "mixed",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sgawa3",
    title: "Help I don't know what to do - Nutrafol and GHK peptide",
    body: "24 year old female, never experienced so much hair loss. I take nutrafol every single day for months. Also just got GHK to try a peptide for my hair. Could be due to stress or IUD. Also take Vyvanse and Ritalin occasionally for ADHD.",
    author: "Backonem",
    score: 1,
    commentCount: 0,
    sentiment: "negative",
    relevantBrands: ["Nutrafol"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sffxjk",
    title: "Toppers/wigs NYC - 6 months of Nutrafol and oral minox not working",
    body: "I feel like the 6 months of nutrafol and 1 month of oral minox aren't doing it and I'm fearing worsened dread shed. I'm at the point where I'm considering an affordable topper or wig just for when I'm going out and want a little bit of confidence.",
    author: "Laputaamadre",
    score: 2,
    commentCount: 2,
    sentiment: "negative",
    relevantBrands: ["Nutrafol"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sct2ap",
    title: "Eyebrow/Hair Loss - alopecia areata from dermatitis",
    body: "It all started in January with a bad flare up of dermatitis. After steroids and prednisone, now using a JAK inhibitor topical ointment opzelura. My bald spot is slightly bigger and eyebrows still shedding. The dermatologist said that the bald spot was officially alopecia areata.",
    author: "GoldenYoshimitsu",
    score: 6,
    commentCount: 16,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1seab5p",
    title: "Should I be worried? More shedding over 7 months",
    body: "I've always had naturally fine hair but noticed more shedding over the past seven months. Lost around 3 kilos. My scalp has become more visible when I pull my hair back. People talk about TE, wondering if that's potentially the case.",
    author: "Odd-Nefariousness455",
    score: 5,
    commentCount: 2,
    sentiment: "neutral",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sgsufz",
    title: "Upped minoxidil dose - experiencing worst shedding ever",
    body: "Had been on 1.25mg since October and recently bumped up to 2.5mg about 3-4 weeks ago. This week I started losing more hair than I have ever lost before. I'm talking 300-400 hairs when I wash. Anyone else experience another dread shed with dose increase?",
    author: "Cheetoh121292",
    score: 2,
    commentCount: 1,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sgs39x",
    title: "6 weeks on 1.25 mg oral minoxidil - AGA and seb derm",
    body: "22F. I have AGA and seb derm. I'm still shedding and don't see much progress after 6 weeks. If anything, the sides and crown look worse to me.",
    author: "iskra-2248",
    score: 1,
    commentCount: 1,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sgrmx7",
    title: "This is just sad - 2 years on minoxidil, still thinning",
    body: "I've been on minoxidil for 2 years and using Vichy Amnixel. Still see some thinning at the crown. The hairstylist at my engagement was making fun of my hair, telling me that I have thin hair, and she ruined my day.",
    author: "catmAmma162",
    score: 1,
    commentCount: 1,
    sentiment: "negative",
    relevantBrands: ["Vichy"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1scht1x",
    title: "When to decide whether medical treatment vs natural remedies",
    body: "Discussion about when to see a dermatologist vs try natural treatments. Top comment: 'You're basically asking whether you should seek scientific vs vibes based treatment. There are a lot of snakeoil salesmen who will sell you natural hair loss treatments.'",
    author: "user",
    score: 3,
    commentCount: 5,
    sentiment: "neutral",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sgq3rp",
    title: "PCOS, almost all hair fell out - Diane 35?",
    body: "Ten years ago diagnosed with PCOS. Androgen levels very high - twice normal male count. Using minoxidil 5%, spironolactone, mio inositol for years and it not only doesn't help but hasn't stopped at all. Only thing left is Diane 35.",
    author: "One-Research-5139",
    score: 1,
    commentCount: 2,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1saf30t",
    title: "Iron supplements and shedding timeline",
    body: "How long after taking iron supplements do you see a decrease in shedding and how long for regrowth? I've been actively shedding tons of hair since a month and have lost so much of my hair density.",
    author: "shopper2907",
    score: 3,
    commentCount: 4,
    sentiment: "neutral",
    relevantBrands: [],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sdedwt",
    title: "Honestly this is so crushing even on oral and topical minoxidil + spironolactone",
    body: "Major thread about the emotional toll of hair loss even while on treatment. High engagement. Comments discuss baby hairs growing, Toppik hair fibers, contrast between hair/scalp color. 'I've been fighting thinning hair in my crown for years.'",
    author: "user",
    score: 50,
    commentCount: 20,
    sentiment: "mixed",
    relevantBrands: ["Toppik"],
  },
  {
    subreddit: "FemaleHairLoss",
    threadId: "1sbyotd",
    title: "Hairloss from inflammation - trichologist-recommended products",
    body: "Using XTC brand DHT shampoo, scalp prep, multivitamin similar to Nutrafol with saw palmetto berry. Also HairStem Scalp Spray and NutraM Scalp Serum from Advanced Trichology. Working on nutritional/vitamin deficiencies with liquid D3+K2.",
    author: "doyouseewhatihear",
    score: 3,
    commentCount: 5,
    sentiment: "neutral",
    relevantBrands: ["Nutrafol"],
  },
  // ─── r/Haircare ─────────────────────────────────────────
  {
    subreddit: "Haircare",
    threadId: "1sf4313",
    title: "Best hair oils for hair regrowth?",
    body: "Over the last few months I've noticed my hair has been thinning. I've struggled with hormonal imbalances. There are so many products and so much research into which ingredients are best (rosemary oil, caffeine, etc). Which hair oil do you swear by?",
    author: "Hot_Establishment911",
    score: 1,
    commentCount: 6,
    sentiment: "neutral",
    relevantBrands: [],
  },
  {
    subreddit: "Haircare",
    threadId: "1sg89ju",
    title: "Hair tool SOS - thinning from GLP-1",
    body: "I have super thinning hair from GLP-1. It's super straggly on the ends. I know it will grow back but in the meantime I don't want to look like a drowned rat. I really want a curling iron that lets me curl it and look nice. I don't feel pretty.",
    author: "Agreeable-Ad2006",
    score: 1,
    commentCount: 1,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "Haircare",
    threadId: "1ses26s",
    title: "Any tips on how to grow more hair - comprehensive treatment guide",
    body: "Detailed comment listing scientifically supported oils (peppermint, pumpkin seed, rosemary), washing guidance, glycolic acid rinse, DHT blockers, microneedling, and topical serums: Minoxidil 5% as the 'cadillac of regrowth', Aminexil (L'Oreal Density Booster), The Ordinary Multi-Peptide Serum for Hair Density, Nioxin treatments.",
    author: "SarahIsJustHere",
    score: 1,
    commentCount: 5,
    sentiment: "neutral",
    relevantBrands: ["The Ordinary", "Nioxin", "L'Oreal Elvive"],
  },
  {
    subreddit: "Haircare",
    threadId: "1sfv6xe",
    title: "Dry Scalp and white flakes - considering Kérastase scalp serum",
    body: "Dealing with dry scalp for a few months and white flakes. Fine, long hair that gets oily quickly. I've come across the Kérastase Nutritive scalp serum. Do you think it would help?",
    author: "kanapka1998",
    score: 1,
    commentCount: 1,
    sentiment: "neutral",
    relevantBrands: ["Kerastase"],
  },
  {
    subreddit: "Haircare",
    threadId: "1sgs7fl",
    title: "Dutasteride 2.5 mg Progress (6 months) - remarkable regrowth",
    body: "Male age 49, hair loss since 28. Was on Finasteride 1mg + oral Minoxidil 5mg for 4.5 years with no results. Switched to Dutasteride 2.5mg per day. At 6 months: fully regrown crown and scalp, 100% coverage. Baby hairs starting on hairline and temples. Side effects included erection difficulties and urinary issues that resolved.",
    author: "Glum_Low",
    score: 1,
    commentCount: 1,
    sentiment: "positive",
    relevantBrands: [],
  },
  // ─── r/HaircareScience ──────────────────────────────────
  {
    subreddit: "HaircareScience",
    threadId: "1mtld6y",
    title: "Evidence-based ways to improve hair density?",
    body: "Which scientifically supported topical treatments, nutrition, or lifestyle interventions have been shown through research to enhance hair growth rate or improve follicle strength and overall hair density? Top answers: minoxidil has the most evidence, rosemary oil has weaker evidence, hair density is a genetic trait, lifestyle interventions alone insufficient without treating underlying conditions.",
    author: "fatimaduaa",
    score: 34,
    commentCount: 26,
    sentiment: "neutral",
    relevantBrands: [],
  },
  {
    subreddit: "HaircareScience",
    threadId: "1qfo9wy",
    title: "Opinions on the Pantene Abundant Strong serum for hair loss",
    body: "In-depth science discussion about oxidative stress and hair shedding. Piroctone Olamine shown to reduce shedding in clinical study. Pantene's product based on research but requires full system. Most scalp serum products use alcohol to enhance penetration. Discussion of claims ingredients vs actual efficacy.",
    author: "user",
    score: 10,
    commentCount: 8,
    sentiment: "mixed",
    relevantBrands: ["Pantene"],
  },
  {
    subreddit: "HaircareScience",
    threadId: "1mhp0zy",
    title: "Do scalp oils actually work for growth or is it just marketing?",
    body: "Discussion about whether scalp oils have any scientific backing for hair growth. Comments note studies are mostly done on men. Friend struggling with thinning hair. Debate between evidence-based treatments and traditional remedies.",
    author: "user",
    score: 15,
    commentCount: 12,
    sentiment: "mixed",
    relevantBrands: [],
  },
  // ─── r/longhair ─────────────────────────────────────────
  {
    subreddit: "longhair",
    threadId: "1sbn221",
    title: "Hair Fall SOS - Telogen Effluvium Recovery at 17",
    body: "Lost about half of my hair density from telogen effluvium. Looking for supplements with iron, vitamin C, vitamin D, omega-3s. 17 years old, recently cut hair to shoulder length because of hair fall.",
    author: "Mysterious-Lab4103",
    score: 0,
    commentCount: 2,
    sentiment: "negative",
    relevantBrands: [],
  },
  {
    subreddit: "longhair",
    threadId: "1sgk3xm",
    title: "Kerastase Genesis hair serum - scared of oiliness on thin hair",
    body: "I have thin and oily hair. Is the Kerastase Genesis hair serum good or not? I am scared it will make hair oily.",
    author: "Traditional-Love949",
    score: 1,
    commentCount: 0,
    sentiment: "neutral",
    relevantBrands: ["Kerastase"],
  },
  // ─── r/Wavyhair ─────────────────────────────────────────
  {
    subreddit: "Wavyhair",
    threadId: "1puezfo",
    title: "JVN air dry cream gone awry - postpartum fine hair struggles",
    body: "Low porosity 2A-2B fine hair. Just had a baby one year ago, so RIP hair density. Went through hormone hell. Found JVN cream too heavy - made hair greasy/flat. Looking for lightweight products for fine wavy hair that don't weigh it down.",
    author: "anemonemonemnea",
    score: 29,
    commentCount: 45,
    sentiment: "mixed",
    relevantBrands: ["JVN"],
  },
  // ─── r/DaniAustin ──────────────────────────────────────
  {
    subreddit: "DaniAustin",
    threadId: "1raw1xf",
    title: "This is Divi hard at work - skepticism about Divi scalp serum",
    body: "Discussion about Divi founder Dani Austin. Comment: 'I got gifted her scalp serum. It does nothing for my hair, but the tingle I get from it helps with migraines.' General skepticism about Divi's marketing claims.",
    author: "user",
    score: 20,
    commentCount: 15,
    sentiment: "negative",
    relevantBrands: ["Divi"],
  },
  // ─── r/curlyhair ────────────────────────────────────────
  {
    subreddit: "curlyhair",
    threadId: "1sguwbo",
    title: "Curl Bites & Umberto Giannini - shedding more hair in shower",
    body: "3B/3C curls, thin strands, medium porosity. I've been shedding more hair in the shower recently. Mainly looking for something that doesn't increase hair shedding, keeps curls defined with low frizz, gives volume without weighing hair down.",
    author: "butch_wannabe",
    score: 1,
    commentCount: 1,
    sentiment: "neutral",
    relevantBrands: [],
  },
];

async function seed() {
  console.log(`Inserting ${threads.length} Reddit threads...`);

  const values = threads.map((t) => ({
    subreddit: t.subreddit,
    threadId: t.threadId,
    title: t.title,
    body: t.body,
    author: t.author,
    score: t.score,
    commentCount: t.commentCount,
    sentiment: t.sentiment,
    relevantBrands: JSON.stringify(t.relevantBrands),
    foundAt: new Date().toISOString(),
  }));

  db.insert(redditThreads).values(values).run();

  // Verify
  const bySubreddit = db
    .select({
      subreddit: redditThreads.subreddit,
      count: sql<number>`COUNT(*)`,
      avgScore: sql<number>`ROUND(AVG(${redditThreads.score}), 1)`,
    })
    .from(redditThreads)
    .groupBy(redditThreads.subreddit)
    .all();

  console.log("\nThreads by subreddit:");
  console.table(bySubreddit);

  const bySentiment = db
    .select({
      sentiment: redditThreads.sentiment,
      count: sql<number>`COUNT(*)`,
    })
    .from(redditThreads)
    .groupBy(redditThreads.sentiment)
    .all();

  console.log("\nThreads by sentiment:");
  console.table(bySentiment);

  console.log("\nDone!");
}

seed().catch(console.error);
